package com.zonesun.daiqian.entity;

public class CreditCard3 {

	private String DDTRXTYPE;// 自动还款交易类型
	private String OUTACCTYPE1;// 自动还款转出帐户类型1
	private String OUTACCTYPE2;// 自动还款转出帐户类型2
	private String OUTCARDNO1;// 转出卡号/帐号1
	private String OUTCARDNO2;// 转出卡号/帐号2
	private String DDAMTTYPE2;// 还款金额类型2
	private String PAYDAYS;// 提前还款天数
	private String PARTPAYF1;// 部分还款1
	private String PARTPAYF2;// 部分还款2
	private String MACHGF;// 主卡开通余额变动提醒
	private String MAMOBILE;// 主卡发送移动电话
	private String MARMBAMT;// 主卡人民币定制金额
	private String MAFORAMT;// 主卡外币定制金额
	private String DECHGF1;// 副卡一开通余额变动提醒
	private String DEMOBILE1;// 副卡一发送移动电话
	private String DERMBAMT1;// 副卡一人民币定制金额
	private String DEFORAMT1;// 副卡一外币定制金额
	private String DECALLF1;// 副卡一短信定制期限
	private String DECALLEXF1;// 副卡一短信自动展期
	private String DECHGF2;// 副卡二开通余额变动提醒
	private String DEMOBILE2;// 副卡二发送移动电话
	private String DERMBAMT2;// 副卡二人民币定制金额
	private String DEFORAMT2;// 副卡二外币定制金额
	private String DECALLF2;// 副卡二短信定制期限
	private String DECALLEXF2;// 副卡二短信自动展期
	private String EMLADDRF;// 开通email对账单
	private String STMTEMAIL;// 对帐单EMAIL
	private String WARDIDTYPE;// 监护人证件类型
	private String WARDIDCODE;// 监护人证件号码
	private String WARDCHSNAME;// 监护人姓名
	private String DEWARDIDTY1;// 副卡一监护人证件类型
	private String DEWARDID1;// 副卡一监护人证件号码
	private String DEWARDNAME1;// 副卡一监护人姓名
	private String DEWARDIDTY2;// 副卡二监护人证件类型
	private String DEWARDID2;// 副卡二监护人证件号码
	private String DEWARDNAME2;// 副卡二监护人姓名
	private String OUTCASHEXF1;// 转出方钞汇标志1
	private String OUTCASHEXF2;// 转出方钞汇标志2
	private String LOWTRAMT;// 自动还款余额标准
	private String TRANAMT;// 还款后帐户余额
	private String PICNO;// 图片编码
	private String PICNO1;// 副卡1图片编码
	private String PICNO2;// 副卡2图片编码
	private String SCDMDU;// 发附属卡标志
	private String SCDMDU1;// 副卡1发附属卡标志
	private String SCDMDU2;// 副卡2发附属卡标志
	private String SICNNO;// 主卡附属卡个性化编码
	private String SICNNO1;// 副卡1附属卡个性化编码
	private String SICNNO2;// 副卡2附属卡个性化编码
	private String SPICNO;// 主卡附属卡图片编码
	private String SPICNO1;// 副卡1附属卡图片编码
	private String SPICNO2;// 副卡2附属卡图片编码
	private String SMSADDRF;// 开通短信对账单
	private String SMSPHONE;// 发送短信帐单手机号码
	private String QESNO;// 问题编号
	private String ANSWER;// 问题答案
	private String CRDRFLAG;// 产品标志
	private String CRDRFLAG1;// 副卡一产品标志
	private String CRDRFLAG2;// 副卡二产品标志
	private String SCRDRFLAG;// 附属卡产品标志
	private String SCRDRFLAG1;// 副卡一附属卡产品标志
	private String SCRDRFLAG2;// 副卡二附属卡产品标志
	private String CRDROPF;// 借记贷记联动开关
	private String CRDROPF1;// 副卡一借记贷记联动开关
	private String CRDROPF2;// 副卡二借记贷记联动开关
	private String SCRDROPF;// 附属卡借记贷记联动开关
	private String SCRDROPF1;// 副卡一附属卡借记贷记联动开关
	private String SCRDROPF2;// 副卡二附属卡借记贷记联动开关
	private String FUNDOPF;// 批量资金归集开关
	private String FUNDOPF1;// 副卡一批量资金归集开关
	private String FUNDOPF2;// 副卡二批量资金归集开关
	private String SFUNDOPF;// 附属卡批量资金归集开关
	private String SFUNDOPF1;// 副卡一附属卡批量资金归集开关
	private String SFUNDOPF2;// 副卡二附属卡批量资金归集开关
	private String FCRDROPF;// 借记贷记联动开关(外币)
	private String FCRDROPF1;// 副卡一借记贷记联动开关(外币)
	private String FCRDROPF2;// 副卡二借记贷记联动开关(外币)
	private String SFCRDROPF;// 附属卡借记贷记联动开关(外币)
	private String SFCRDROPF1;// 副卡一附属卡借记贷记联动开关(外币)
	private String SFCRDROPF2;// 副卡二附属卡借记贷记联动开关(外币)
	private String FFUNDOPF;// 批量资金归集开关(外币)
	private String FFUNDOPF1;// 副卡一批量资金归集开关(外币)
	private String FFUNDOPF2;// 副卡二批量资金归集开关(外币)
	private String SFFUNDOPF;// 附属卡批量资金归集开关(外币)
	private String SFFUNDOPF1;// 副卡一附属卡批量资金归集开关(外币)
	private String SFFUNDOPF2;// 副卡二附属卡批量资金归集开关(外币)
	private String CITYNO;// 城市圈编号
	private String CHKFLG;// 联网核查结果
	private String DECHKFLG1;// 副卡1联网核查结果
	private String DECHKFLG2;// 副卡2联网核查结果
	private String CHKDESC;// 核查结果说明
	private String DECHKDESC1;// 副卡1核查结果说明
	private String DECHKDESC2;// 副卡2核查结果说明
	private String SIGNFLG;// 亲见客户签名
	private String DESIGNFLG1;// 副卡1亲见客户签名
	private String DESIGNFLG2;// 副卡2亲见客户签名
	private String ATMTXFLG;// ATM转帐标志
	private String DEATMTXFLG1;// 副卡1ATM转帐标志
	private String DEATMTXFLG2;// 副卡2ATM转帐标志

}
